### ISSUE TITLE
腾讯云函数完整配完了，请求返回Forbidden

### ISSUE THREAD

**Issue by tzxylao** [easychen/openai-api-proxy#10]
腾讯云函数完整配完了，请求返回Forbidden

**Comment by easychen** [comment]
所以你传key了吗？

**Comment by hnboy2005** [comment]
同样的问题

**Comment by tzxylao** [comment]
我大概知道了意思了，这里用腾讯云函数，是可以通过它的链接用api调用外网接口。我以为可以网址转接访问chatgpt，如果只是调api，那是需要开发相关应用或工具才需要用到，我是没必要了。。建议说明里写一条，用于调Api

**Comment by easychen** [comment]
![image](https://user-images.githubusercontent.com/1294760/224520894-52e86503-9294-492d-997a-db9b318090d1.png)

有写啊 🤣
