### ISSUE TITLE
请问是否支持代理中转长链接的流式输出(打字效果)？

### ISSUE THREAD

**Issue by ZhuningS** [easychen/openai-api-proxy#13]
（H5流式输出，通过长链接实时文本事件流实现动态数据展示）？ 基于websocket实现的SSE(server-sent events技术)实时输出。[EventSource](https://developer.mozilla.org/zh-CN/docs/Web/API/EventSource) 。
目前已知云函数无法支持代理中转这种链接。

**Comment by easychen** [comment]
首先SSE并不是基于websocket协议的。然后，仓库首页有说明，本项目本身是支持SSE的，可以通过本地docker镜像验证。

腾讯云函数不支持是环境的问题，并不是代码实现的问题。
