### ISSUE TITLE
报错code: "ETIMEDOUT"

### ISSUE THREAD

**Issue by ZhuningS** [easychen/openai-api-proxy#14]
本地ping 服务器ip正常，在uniapp做的微信公众号H5项目上请求报如下错误。在postman里也是超时. 阿里云安全组和linux防火墙已经开放9000端口
code: "ETIMEDOUT"
message: "connect ETIMEDOUT xxx.xxxx.xxxx.xxx:9000, POST http://xxx.xxxx.xxxx.xxx:9000/chat -1 (connected: false, keepalive socket: false, socketHandledRequests: 1, socketHandledResponses: 0)↵headers: {}"‘

**Comment by easychen** [comment]
这看起来是部署的问题。

如果你在本地测试OK，部署到云上有问题，那么显然是部署得不对，给软件提issue并不能解决部署的问题。

**Comment by ZhuningS** [comment]
本地测试了一下，提示"Forbidden"
