### ISSUE TITLE
docker 部署设置环境变量失败

### ISSUE THREAD

**Issue by ZhuningS** [easychen/openai-api-proxy#15]
docker run -d -p 9000:9000 easychen/ai.level06.com:latest -e TIMEOUT=120000 设置环境变量失败

**Comment by easychen** [comment]
![image](https://user-images.githubusercontent.com/1294760/225549424-9618e653-efe8-410d-9030-5a36c5850bef.png)

**Comment by ZhuningS** [comment]
哦哦 不好意思
