### ISSUE TITLE
用docker部署为什么是Forbidden

### ISSUE THREAD

**Issue by 1412kid** [easychen/openai-api-proxy#31]

**Comment by easychen** [comment]
因为它是api 代理，你不带参数访问就是 forbidden。

**Comment by 1412kid** [comment]
我把ip地址+端口放在 chatbox里是获取不到内容的，我用腾讯云函数的地址可以获取到， 只不过云函数有点慢

Easy ***@***.***> 于2023年4月16日周日 19:05写道：
