### ISSUE TITLE
这一条docker命令到底行不行啊

### ISSUE THREAD

**Issue by 1412kid** [easychen/openai-api-proxy#32]
用云函数能部署成功，把地址放在各种第三方插件里都能请求到内容，用docker部署的根本请求不到内容，这docker行不行啊，docker部署完后的地址+端口不根腾讯云函数的那个地址一样吗？

**Comment by easychen** [comment]
<img width="658" alt="image" src="https://user-images.githubusercontent.com/1294760/232315389-53309125-a71e-4a83-9597-8bc1d16f78ab.png">

实测没有问题。
