### ISSUE TITLE
腾讯云函数返回432

### ISSUE THREAD

**Issue by litsen** [easychen/openai-api-proxy#5]
腾讯云函数还能用么? 现在是返回403报错, 大神帮忙看看

![image](https://user-images.githubusercontent.com/3929213/223886126-9dae1998-222f-4bd2-bd1e-069719cc2ac5.png)

**Comment by huhongda** [comment]
遇到同样的问题

**Comment by easychen** [comment]
这不写了内存给小了256M不够用么……

**Comment by litsen** [comment]
原来403就可以了, 感谢~
