### ISSUE TITLE
腾讯云函数不支持SSE？

### ISSUE THREAD

**Issue by geek-longbeard** [easychen/openai-api-proxy#7]
我通过腾讯云函数的脚本完成了云函数部署，但是我本地跑了一个服务，调用 openai 的接口是能实现 SSE，但是切换成 云函数的接口后反而不能实现服务器推了？这个还需要做什么配置么？

**Comment by easychen** [comment]
① 本地测试下 docker 版 ② 如果docker版没问题，那么请给腾讯云提issue。

**Comment by huhongda** [comment]
我测试了一下，docker版本是没问题的，应该是腾讯云的问题，我给腾讯云提issue

**Comment by Jackiexiao** [comment]
这个问题应该跟 aws 云函数类似，都无法支持 SSE
https://github.com/nangcr/chatgpt-aws-proxy/issues/1

**Comment by geek-longbeard** [comment]
咨询了一下腾讯云的支持，目前不支持 SSE，只支持 websocket，所以无解。
